import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import Release from '../pages/admin/Release'

const requests=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn()}))
vi.mock('../lib/api',()=>({api:requests,getErrorMessage:(e:any)=>e?.message||'请求失败'}))
beforeEach(()=>{
  requests.get.mockImplementation(async(path:string)=>({data:path.includes('/catalog/')?{fields:['username','name','role'],required:['username'],items:[{id:'u1',username:'teacher',name:'张老师',role:'teacher',enabled:true}]}:path.endsWith('/source')?{config:{table:'records',fields:{source_record_id:'id'},enabled:false,frequency_hours:24}}:path.endsWith('/status')?{database:'connected',worker:{stale:false},ai:'not_configured'}:path.endsWith('/audit')?[{id:'a1',action:'update',result:'success',actor_name:'管理员',created_at:'2026-10-01'}]:{} }))
  requests.post.mockResolvedValue({data:{success:1}});requests.put.mockResolvedValue({data:{saved:true}})
  URL.createObjectURL=vi.fn(()=> 'blob:download');URL.revokeObjectURL=vi.fn()
  vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{})
})
afterEach(()=>{cleanup();vi.clearAllMocks();vi.restoreAllMocks()})

it('edits account, preserves history, uploads validated files and handles failures',async()=>{
  render(<Release/>);await screen.findByText('张老师')
  fireEvent.click(screen.getByText('张老师'))
  fireEvent.change(screen.getByLabelText('名称'),{target:{value:'李老师'}})
  fireEvent.click(screen.getByRole('button',{name:'保存'}))
  await waitFor(()=>expect(requests.put).toHaveBeenCalledWith('/api/v1/release/catalog/accounts/u1',expect.objectContaining({name:'李老师'})))
  fireEvent.click(screen.getByText('查看修改前后记录'))
  await waitFor(()=>expect(requests.get).toHaveBeenCalledWith('/api/v1/release/versions/accounts/u1'))
  fireEvent.click(screen.getByText('新建另一条'))
  fireEvent.change(screen.getByLabelText(/登录账号/),{target:{value:'newuser'}})
  fireEvent.change(screen.getByLabelText('角色'),{target:{value:'student'}})
  fireEvent.click(screen.getByLabelText('启用'))
  fireEvent.click(screen.getByRole('button',{name:'保存'}))
  await waitFor(()=>expect(requests.post).toHaveBeenCalled())
  const file=new File(['username,name\na,A'],'users.csv',{type:'text/csv'})
  fireEvent.change(screen.getByLabelText('基础数据文件'),{target:{files:[file]}})
  fireEvent.click(screen.getByText('校验文件'))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/catalog/accounts/import',expect.any(FormData),expect.objectContaining({params:{preview:true}})))
  fireEvent.click(screen.getByText('导入有效记录'))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/catalog/accounts/import',expect.any(FormData),expect.objectContaining({params:{preview:false}})))
  fireEvent.click(screen.getByText('下载导入模板'))
  await waitFor(()=>expect(URL.createObjectURL).toHaveBeenCalled())
  requests.post.mockRejectedValueOnce(new Error('记录无效'))
  fireEvent.click(screen.getByRole('button',{name:'保存'}))
  expect(await screen.findByRole('alert')).toHaveTextContent('记录无效')
})

it('configures read-only fields, imports real records, queries audit and creates backup',async()=>{
  render(<Release/>);await screen.findByText('张老师')
  fireEvent.click(screen.getByText('校方数据源'))
  await screen.findByDisplayValue('records')
  fireEvent.change(screen.getByLabelText('表或只读视图名称'),{target:{value:'school_records'}})
  fireEvent.change(screen.getByLabelText('student_no'),{target:{value:'student_number'}})
  fireEvent.change(screen.getByLabelText('自动同步间隔（小时）'),{target:{value:'12'}})
  fireEvent.click(screen.getByLabelText('启用定时同步'))
  fireEvent.click(screen.getByText('保存映射'))
  await waitFor(()=>expect(requests.put).toHaveBeenCalledWith('/api/v1/release/source',expect.objectContaining({table:'school_records',frequency_hours:12,enabled:true})))
  fireEvent.click(screen.getByText('执行一次同步'))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/source/sync',null,{timeout:300000}))
  fireEvent.click(screen.getByText('真实实训导入'))
  fireEvent.click(screen.getByText('下载模板'))
  fireEvent.change(screen.getByLabelText('实训记录文件'),{target:{files:[new File(['x'],'records.csv')]}})
  await waitFor(()=>expect(screen.getByText('导入并计算')).not.toBeDisabled())
  fireEvent.click(screen.getByText('导入并计算'))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/records/import',expect.any(FormData),expect.anything()))
  fireEvent.click(screen.getByText('操作审计'))
  fireEvent.change(screen.getByLabelText('开始时间'),{target:{value:'2026-10-01T00:00'}})
  fireEvent.change(screen.getByLabelText('结束时间'),{target:{value:'2026-10-02T00:00'}})
  fireEvent.click(screen.getByText('查询'))
  await screen.findByText(/管理员 · update/)
  fireEvent.click(screen.getByText('运行与备份'))
  await screen.findByText(/数据库：connected/)
  fireEvent.click(screen.getByText('立即创建加密备份'))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/backups'))
})

it('supports JSON rules and standard-photo upload from the selected lab',async()=>{
  requests.get.mockImplementation(async(path:string)=>({data:path.includes('/projects')?{fields:['steps','scoring_rules','ability_mapping'],required:[],items:[]}:{fields:['name'],required:[],items:[{id:'lab1',name:'第四实训室'}]}}))
  render(<Release/>);await screen.findByText('第四实训室')
  fireEvent.change(screen.getByLabelText('数据类型'),{target:{value:'projects'}})
  const steps=await screen.findByLabelText('操作步骤（JSON）')
  fireEvent.change(steps,{target:{value:'[{"id":"one","score":10}]'}})
  fireEvent.click(screen.getByRole('button',{name:'保存'}))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/catalog/projects',expect.objectContaining({steps:[{id:'one',score:10}]})))
  fireEvent.change(screen.getByLabelText('数据类型'),{target:{value:'labs'}})
  fireEvent.click(await screen.findByText('第四实训室'))
  fireEvent.change(screen.getByLabelText('标准状态图片'),{target:{files:[new File(['image'],'reference.png')]}})
  fireEvent.click(screen.getByText('保存标准状态图片'))
  await waitFor(()=>expect(requests.post).toHaveBeenCalledWith('/api/v1/release/labs/lab1/reference',expect.any(FormData),expect.anything()))
})
